### PR TITLE
update project generator 

### PR DESCRIPTION
**Pull request by qaderi-coding**
The following addition and modification added
1. Smart contract generating prompt added
2. `toPascalCase` custom function added that we need in contract generator  
3. Config data generator functionality added in which we store the user inputs that we can use further 
4. NextApp home page template added along with essential code

### CODE REVIEW

**Review by jordanbaron — COMMENTED** [review]
hey, in the instructions variable for both createHardhat & createNextApp you removed the lines that would generate the app. like i’m createNextApp you removed ‘npx create-next-app’, so how is the next app being generated?

**Comment by qaderi-coding** [comment]
Yes, I am going to add that. Don't worry.
I was just testing the new features. So I didn't want to install the dependencies every time.

**Comment by jordszbordsz** [comment]
> Yes, I am going to add that. Don't worry.
> I was just testing the new features. So I didn't want to install the dependencies every time.

gotcha. i’m assuming you’ve tested them, so if you don’t mind could you go ahead and add them back in then i can merge the PR?

**Comment by qaderi-coding** [comment]
I need some more testing.
Some of the issues are still remaining.
I have the log and I am going to add that in the next pull request.

**Comment by jordszbordsz** [comment]
> I need some more testing.
> Some of the issues are still remaining.
> I have the log and I am going to add that in the next pull request.

gotcha, i could help debug if you want :)

**Pull request merged**
